export const langResources = {
    eng: {
        dashboardTitle: "Personal Account",
        myAccountTab: "My Account",
        partnerTab: "Partner Section",
        profileName: "Oleksandr Smirnov",
        profileEmail: "alex@example.com",
        profilePhotoAlt: "Profile Photo",
        referralCodeLabel: "Your referral code:",
        referralCountLabel: "Number of times your code has been used:",
        referralCodeHint: "Every user who enters your referral code will receive a personal discount!",
        generateCouponButton: "Generate Personal Coupon",
        becomePartnerButton: "Become a Partner",
        discountCouponFormTitle: "Discount Coupon",
        linkedProfilesTitle: "Linked Profiles",
        orderSectionTitle: "Orders",
        supportContactsTitle: "Support Contacts",
        snackbarSuccess: "Personal coupon successfully generated!",
        snackbarError: "Error generating referral code",
        snackbarPartnerSuccess: "You have successfully become a partner!",
        snackbarPartnerError: "Error becoming a partner",
        snackbarInfo: "Selected card with name:",
    },
    ua: {
        dashboardTitle: "Особистий кабінет",
        myAccountTab: "Мій аккаунт",
        partnerTab: "Розділ партнера",
        profileName: "Олександр Смирнов",
        profileEmail: "alex@example.com",
        profilePhotoAlt: "Фото профілю",
        referralCodeLabel: "Ваш реферальний код:",
        referralCountLabel: "Кількість використань вашого коду:",
        referralCodeHint: "Кожен користувач, який введе ваш реферальний код, отримає персональну знижку!",
        generateCouponButton: "Згенерувати персональний купон",
        becomePartnerButton: "Стати партнером",
        discountCouponFormTitle: "Купон на знижку",
        linkedProfilesTitle: "Зв'язані профілі",
        orderSectionTitle: "Замовлення",
        supportContactsTitle: "Контакти підтримки",
        snackbarSuccess: "Персональний купон успішно згенеровано!",
        snackbarError: "Помилка при генерації реферального коду",
        snackbarPartnerSuccess: "Ви успішно стали партнером!",
        snackbarPartnerError: "Помилка при зміні статусу на партнера",
        snackbarInfo: "Вибрано картку з ім'ям:",
    }
};