export const langResources = {
    eng: {
        referralCodeTitle: "Referral Code",
        referralCodeDescription: "Your referral code:",
        referralCodeHint: "When a user enters this code, you will receive a portion of the profit if the user purchases services on the site.",
        addMonumentTitle: "Add your monument or service to the catalog",
        sectionLabel: "Section",
        sectionOptions: {
            granite: "Granite Monuments",
            marble: "Marble Monuments",
            other: "Other Materials",
            services: "Additional Services",
        },
        titleLabel: "Title",
        descriptionLabel: "Description",
        priceLabel: "Price",
        countryLabel: "Country",
        cityLabel: "City",
        uploadPhotoButton: "Upload Photo",
        previewTitle: "Preview before creation",
        addMonumentButton: "Add monument or service",
        snackbarSuccess: "Photo uploaded successfully!",
        snackbarError: "Error uploading photo",
        snackbarMonumentSuccess: "Monument created successfully!",
        snackbarMonumentError: "Error creating monument",
    },
    ua: {
        referralCodeTitle: "Реферальний код",
        referralCodeDescription: "Ваш реферальний код:",
        referralCodeHint: "При введенні цього коду користувачем, ви отримуєте частину прибутку, якщо користувач придбає послуги сайта.",
        addMonumentTitle: "Додати ваш пам'ятник або послугу в каталог",
        sectionLabel: "Секція",
        sectionOptions: {
            granite: "Пам'ятники з граніту",
            marble: "Пам'ятники з мармуру",
            other: "Інші матеріали",
            services: "Додаткові послуги",
        },
        titleLabel: "Назва",
        descriptionLabel: "Опис",
        priceLabel: "Ціна",
        countryLabel: "Країна",
        cityLabel: "Місто",
        uploadPhotoButton: "Завантажити фото",
        previewTitle: "Попередній перегляд перед створенням",
        addMonumentButton: "Додати пам'ятник або послугу",
        snackbarSuccess: "Фото успішно завантажено!",
        snackbarError: "Помилка при завантаженні фото",
        snackbarMonumentSuccess: "Пам'ятник успішно створено!",
        snackbarMonumentError: "Помилка при створенні пам'ятника",
    }
};