export const langResources = {
    eng: {
        partnerPresentationTitle: "Presentation for Monument Manufacturing Partners",
        collaborationTitle: "Collaboration with our service: new opportunities for your business",
        whatWeOffer: "What do we offer?",
        whatWeOfferText: "We have created a unique online service where anyone can register memories of their loved ones by adding their photos, videos, biography, and receive a QR code for quick access to this information.",
        howItWorks: "How does it work for you?",
        howItWorksText: "You can offer your clients not only monuments but also the opportunity to create a digital memory of their loved ones.",
        referralProgram: "Referral Program",
        referralProgramText: "The more clients you bring, the higher your profit:",
        benefitsForYou: "Benefits for you:",
        benefitsList: [
            "✔ Additional passive income",
            "✔ Increased value of your service",
            "✔ Simple process with no additional costs",
            "✔ Customer loyalty through discounts",
        ],
        howToStart: "How to start?",
        howToStartList: [
            "Above or in your personal account, you can see your personal referral code. When a user enters your code, they receive a 5% discount, and you receive your profit.",
            "Start recommending our service to your clients.",
            "Earn bonuses and expand your business opportunities!",
        ],
        referralTiers: [
            "Up to 10 clients per month – 10%",
            "Up to 20 clients per month – 15%",
            "Up to 30 clients per month – 20%",
            "More than 30 clients per month – 25% (maximum)",
        ],
    },
    ua: {
        partnerPresentationTitle: "Презентація для партнерів з виготовлення пам'ятників",
        collaborationTitle: "Співпраця з нашим сервісом: нові можливості для вашого бізнесу",
        whatWeOffer: "Що ми пропонуємо?",
        whatWeOfferText: "Ми створили унікальний онлайн-сервіс, де кожен може зареєструвати пам'ять про своїх близьких, додавши їхні фото, відео, біографію та отримати QR-код для швидкого доступу до цієї інформації.",
        howItWorks: "Як це працює для вас?",
        howItWorksText: "Ви можете пропонувати своїм клієнтам не лише пам’ятники, а й можливість створення цифрової пам’яті про їхніх рідних.",
        referralProgram: "Реферальна програма",
        referralProgramText: "Чим більше клієнтів ви приводите – тим більший ваш прибуток:",
        benefitsForYou: "Переваги для вас:",
        benefitsList: [
            "✔ Додатковий пасивний дохід",
            "✔ Збільшення цінності вашої послуги",
            "✔ Простий процес без додаткових витрат",
            "✔ Лояльність клієнтів через надання знижок",
        ],
        howToStart: "Як почати?",
        howToStartList: [
            "Вище або у вашому особистому кабінеті ви можете бачити ваш персональний реферальний код. Користувач при вводі вашого коду отримує знижку 5 відсотків, а ви отримуєте ваш прибуток.",
            "Почніть рекомендувати наш сервіс вашим клієнтам.",
            "Отримуйте бонуси та розширюйте можливості вашого бізнесу!",
        ],
        referralTiers: [
            "до 10 клієнтів на місяць – 10%",
            "до 20 клієнтів на місяць – 15%",
            "до 30 клієнтів на місяць – 20%",
            "більше 30 клієнтів на місяць – 25% (максимум)",
        ],
    }
};