export const langResources = {
    eng: {
        createPageTitle: "CREATE A MEMORIAL PAGE",
        memorialPhoto: "MEMORIAL PHOTO",
        photoDescription: "Choose the best photo by clicking on the icon on the left, the photo will be displayed at the top of the memorial page",
        fullName: "Last name, first name, patronymic",
        birthDate: "Date of birth",
        deathDate: "Date of death",
        epitaph: "Epitaph",
        memorialWords: "Memorial words",
        addGallery: "Add a photo gallery",
        youtubeLink: "Link to a YouTube video (optional)",
        videoPreview: "Video preview:",
        invalidYoutubeLink: "Invalid YouTube link. Please enter a valid URL.",
        videoInstruction: "Video instruction:",
        qrCode: "QR code link to this page",
        price: "1200 UAH",
        payButton: "Pay",
        quote: "\"For to me, to live is Christ and to die is gain.\"",
        quoteSource: "Philippians 1:21",
    },
    ua: {
        createPageTitle: "СТВОРЕННЯ СТОРІНКИ ПАМ'ЯТІ",
        memorialPhoto: "ПАМ'ЯТНЕ ФОТО",
        photoDescription: "Виберіть найкраще фото натиснивши на іконку лівіше, фото буде відображене на початку пам'ятної сторінки",
        fullName: "Прізвище, ім'я, по-батькові",
        birthDate: "Дата народження",
        deathDate: "Дата смерті",
        epitaph: "Епітафія",
        memorialWords: "Пам'ятні слова",
        addGallery: "Додайте галерею фотографій",
        youtubeLink: "Посилання на відео з YouTube (по-бажанню)",
        videoPreview: "Прев'ю відео:",
        invalidYoutubeLink: "Невірне посилання на YouTube. Будь ласка, введіть коректну URL-адресу.",
        videoInstruction: "Відео інструкція:",
        qrCode: "QR-код посилання на цю сторінку",
        price: "1200 грн",
        payButton: "Оплатити",
        quote: "\"Бо для мене життя — Христос, а смерть — набуття.\"",
        quoteSource: "Филип'ян 1:21",
    }
};