export const langResources = {
    eng: {
        registration: "Registration",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phoneNumber: "Phone Number",
        enterPassword: "Enter Password",
        confirmPassword: "Confirm Password",
        register: "Register",
        registerWithGoogle: "Register with Google",
        alreadyHaveAccount: "Already have an account?",
        loginHere: "Login here",
        passwordsDoNotMatch: "Passwords do not match!",
        registrationSuccess: "Registration successful!",
        googleRegistrationSuccess: "Google registration successful!",
        googleRegistrationError: "Google registration error",
        userExists: "User with this email already exists",
        serverError: "Could not connect to the server."
    },
    ua: {
        registration: "Реєстрація",
        firstName: "Ім'я",
        lastName: "Прізвище",
        email: "Email",
        phoneNumber: "Номер телефона",
        enterPassword: "Введіть пароль",
        confirmPassword: "Підтвердіть пароль",
        register: "Зареєструватися",
        registerWithGoogle: "Реєстрація через Google",
        alreadyHaveAccount: "Вже є акаунт?",
        loginHere: "Увійдіть тут",
        passwordsDoNotMatch: "Паролі не збігаються!",
        registrationSuccess: "Реєстрація успішна!",
        googleRegistrationSuccess: "Реєстрація через Google успішна!",
        googleRegistrationError: "Помилка реєстрації через Google",
        userExists: "Користувач з таким email вже існує",
        serverError: "Не вдалося зв'язатися з сервером."
    }
};